/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alu20491147x
 */
public class CustomSettingsDialog extends javax.swing.JDialog {
    
    Board board;

    /**
     * Creates new form CustomSettingsDialog
     */
    public CustomSettingsDialog(java.awt.Frame parent, boolean modal, Board board) {
        super(parent, modal);
        setLocationRelativeTo(null);
        this.board = board;
        initComponents();
    }
    
    public void getValues() {
        ConfigSingleton cs = ConfigSingleton.getInstance();
        cs.setDeltaTime(Integer.parseInt(deltaTimeTextField.getText()));
        cs.setNumRows(Integer.parseInt(rowsTextField.getText()));
        cs.setNumCols(Integer.parseInt(colsTextField.getText()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanelBackGround1 = new ImagePanelBackGround();
        numRowsLabel = new javax.swing.JLabel();
        numColsLabel = new javax.swing.JLabel();
        deltaTimeLabel = new javax.swing.JLabel();
        rowsTextField = new javax.swing.JTextField();
        colsTextField = new javax.swing.JTextField();
        deltaTimeTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        numRowsLabel.setFont(new java.awt.Font("Noto Mono", 1, 14)); // NOI18N
        numRowsLabel.setText("Number of Rows :");

        numColsLabel.setFont(new java.awt.Font("Noto Mono", 1, 14)); // NOI18N
        numColsLabel.setText("Number of Columns :");

        deltaTimeLabel.setFont(new java.awt.Font("Noto Mono", 1, 14)); // NOI18N
        deltaTimeLabel.setText("Speed :");

        rowsTextField.setText("30");

        colsTextField.setText("30");

        deltaTimeTextField.setText("200");

        jLabel1.setFont(new java.awt.Font("Noto Mono", 1, 10)); // NOI18N
        jLabel1.setText("(Default: 30)");

        jLabel2.setFont(new java.awt.Font("Noto Mono", 1, 10)); // NOI18N
        jLabel2.setText("(Default: 30)");

        jLabel3.setFont(new java.awt.Font("Noto Mono", 1, 10)); // NOI18N
        jLabel3.setText("(Less is more speed)");

        confirmButton.setBackground(new java.awt.Color(255, 204, 0));
        confirmButton.setFont(new java.awt.Font("Noto Mono", 1, 14)); // NOI18N
        confirmButton.setText("CONFIRM AND START");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout imagePanelBackGround1Layout = new javax.swing.GroupLayout(imagePanelBackGround1);
        imagePanelBackGround1.setLayout(imagePanelBackGround1Layout);
        imagePanelBackGround1Layout.setHorizontalGroup(
            imagePanelBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanelBackGround1Layout.createSequentialGroup()
                .addGroup(imagePanelBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imagePanelBackGround1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(imagePanelBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(imagePanelBackGround1Layout.createSequentialGroup()
                                .addGroup(imagePanelBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(numColsLabel)
                                    .addComponent(numRowsLabel)
                                    .addComponent(deltaTimeLabel)
                                    .addGroup(imagePanelBackGround1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(11, 11, 11)))
                                .addGap(51, 51, 51)
                                .addGroup(imagePanelBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(imagePanelBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(colsTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(rowsTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                                    .addComponent(deltaTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(imagePanelBackGround1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(confirmButton))))
                    .addGroup(imagePanelBackGround1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(imagePanelBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        imagePanelBackGround1Layout.setVerticalGroup(
            imagePanelBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanelBackGround1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(imagePanelBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numRowsLabel)
                    .addComponent(rowsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(imagePanelBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numColsLabel))
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(imagePanelBackGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deltaTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deltaTimeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(confirmButton)
                .addContainerGap())
        );

        getContentPane().add(imagePanelBackGround1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        getValues();
        dispose();
        board.initCounter();
    }//GEN-LAST:event_confirmButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField colsTextField;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel deltaTimeLabel;
    private javax.swing.JTextField deltaTimeTextField;
    private ImagePanelBackGround imagePanelBackGround1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel numColsLabel;
    private javax.swing.JLabel numRowsLabel;
    private javax.swing.JTextField rowsTextField;
    // End of variables declaration//GEN-END:variables
}
